services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
      - api03
    network_mode: host
    restart: unless-stopped

  api01: &api
    build: .
    command: /main -port 8081
    expose:
      - 8081
    network_mode: host
    restart: unless-stopped

  api02:
    <<: *api
    command: /main -port 8083
    depends_on:
      - api01
    expose:
      - 8082

  api03:
    <<: *api
    command: /main -port 8082
    depends_on:
      - api02
    expose:
      - 8082

# volumes:
#   database:
#     driver: local
